config/routes.rb
Cryout::Application.routes.draw do
  resources :organisers

  resources :coordinators

  resources :counties

  resources :states

  devise_for :users

	match 'states/export' => 'state#export'

   root :to => "states#index"

end

app/models/organiser.rb
class Organiser < ActiveRecord::Base
	belongs_to :state
end

app/controllers/organisers_controller.rb
class OrganisersController < ApplicationController
  # GET /organisers
  # GET /organisers.xml
  def index
    @organisers = Organiser.all
		@states = State.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @organisers }
    end
  end

  # GET /organisers/1
  # GET /organisers/1.xml
  def show
    @state = State.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @organiser }
    end
  end

  # GET /organisers/new
  # GET /organisers/new.xml
  def new
    @organiser = Organiser.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @organiser }
    end
  end

  # GET /organisers/1/edit
  def edit
    @organiser = Organiser.find(params[:id])
  end

  # POST /organisers
  # POST /organisers.xml
  def create
    @organiser = Organiser.new(params[:organiser])

    respond_to do |format|
      if @organiser.save
        format.html { redirect_to(@organiser, :notice => 'Organiser was successfully created.') }
        format.xml  { render :xml => @organiser, :status => :created, :location => @organiser }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @organiser.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /organisers/1
  # PUT /organisers/1.xml
  def update
    @organiser = Organiser.find(params[:id])

    respond_to do |format|
      if @organiser.update_attributes(params[:organiser])
        format.html { redirect_to(@organiser, :notice => 'Organiser was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @organiser.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /organisers/1
  # DELETE /organisers/1.xml
  def destroy
    @organiser = Organiser.find(params[:id])
    @organiser.destroy

    respond_to do |format|
      format.html { redirect_to(organisers_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/organisers_helper.rb
module OrganisersHelper
end

app/views/organisers/_form.html.erb
<%= form_for(@organiser) do |f| %>
  <% if @organiser.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@organiser.errors.count, "error") %> prohibited this organiser from being saved:</h2>

      <ul>
      <% @organiser.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstname %><br />
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br />
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :street %><br />
    <%= f.text_field :street %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state_id %><br />
    <%= f.text_field :state_id %>
  </div>
  <div class="field">
    <%= f.label :zipcode %><br />
    <%= f.text_field :zipcode %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/organisers/edit.html.erb
<h1>Editing organiser</h1>

<%= render 'form' %>

<%= link_to 'Show', @organiser %> |
<%= link_to 'Back', organisers_path %>

app/views/organisers/index.html.erb
<h1>Listing organisers</h1>

<table>
  <tr>
    <th>Firstname</th>
    <th>Lastname</th>
    <th>Email</th>
    <th>Phone</th>
    <th>Street</th>
    <th>City</th>
    <th>State</th>
    <th>Zipcode</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @organisers.each do |organiser| %>
  <tr>
    <td><%= organiser.firstname %></td>
    <td><%= organiser.lastname %></td>
    <td><%= organiser.email %></td>
    <td><%= organiser.phone %></td>
    <td><%= organiser.street %></td>
    <td><%= organiser.city %></td>
    <td><%= organiser.state_id %></td>
    <td><%= organiser.zipcode %></td>
    <td><%= link_to 'Show', organiser %></td>
    <td><%= link_to 'Edit', edit_organiser_path(organiser) %></td>
    <td><%= link_to 'Destroy', organiser, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Organiser', new_organiser_path %>

app/views/organisers/new.html.erb
<h1>New organiser</h1>

<%= render 'form' %>

<%= link_to 'Back', organisers_path %>

app/views/organisers/show.html.erb
<p id="notice"><%= notice %></p>
<% if @state.organiser %>
<h2><%= @state.name %> State Coordinator</h2>
<p><strong><%= @state.organiser.firstname %> <%= @state.organiser.lastname%></strong> is serving as the state coordinator for <%= @state.name %>. <br />
<%= @state.organiser.phone %><br />
<a href="mailto:<%= @state.organiser.email %>"><%= @state.organiser.email %></p>

<% else %>
<h2><%= @state.name %></h2>
<p>This State Needs a Coordinator! You can submit your application below:</p>
<script type="text/javascript">var host = (("https:" == document.location.protocol) ? "https://secure." : "http://");document.write(unescape("%3Cscript src='" + host + "wufoo.com/scripts/embed/form.js' type='text/javascript'%3E%3C/script%3E"));</script><script type="text/javascript">
var m7p2a3 = new WufooForm();
m7p2a3.initialize({
'userName':'socialmedia101', 
'formHash':'m7p2a3', 
'autoResize':true,
'height':'846', 
'ssl':true});
m7p2a3.display();
</script>
<% end %>