config/routes.rb
Cryout::Application.routes.draw do
  resources :organisers

  resources :coordinators

  resources :counties

  resources :states

  devise_for :users

	match 'states/export' => 'state#export'

   root :to => "states#index"

end

app/models/coordinator.rb
class Coordinator < ActiveRecord::Base
	belongs_to :county
	belongs_to :state





end

app/controllers/coordinators_controller.rb
class CoordinatorsController < ApplicationController
  # GET /coordinators
  # GET /coordinators.xml
  def index
    @coordinators = Coordinator.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @coordinators }
			format.csv  { render :csv => @coordinators }
    end
  end

  # GET /coordinators/1
  # GET /coordinators/1.xml
  def show
    @coordinator = Coordinator.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @coordinator }
    end
  end

  # GET /coordinators/new
  # GET /coordinators/new.xml
  def new
    @coordinator = Coordinator.new
		@county = County.find(params[:county_id])

  end

  # GET /coordinators/1/edit
  def edit
    @coordinator = Coordinator.find(params[:id])
  end

  # POST /coordinators
  # POST /coordinators.xml
  def create
		@county = County.find(params['coordinator']['county_id'])
		@coordinator = @county.build_coordinator(params[:coordinator]) 
      if @coordinator.save
        redirect_to(@county, :notice => 'Thank you for your application. We will respond as soon as possible!')
				CoordinatorMailer.registration_confirmation(@coordinator).deliver
				CoordinatorMailer.registration_notification(@coordinator).deliver
      else
         render :action => "new"

   	  end
  end

  # PUT /coordinators/1
  # PUT /coordinators/1.xml
  def update
    @coordinator = Coordinator.find(params[:id])

    respond_to do |format|
      if @coordinator.update_attributes(params[:coordinator])
        format.html { redirect_to(@coordinator, :notice => 'Coordinator was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @coordinator.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /coordinators/1
  # DELETE /coordinators/1.xml
  def destroy
    @coordinator = Coordinator.find(params[:id])
    @coordinator.destroy

    respond_to do |format|
      format.html { redirect_to(coordinators_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/coordinators_helper.rb
module CoordinatorsHelper
end

app/views/coordinators/_form.html.erb
<%= form_for(@coordinator) do |f| %>
  <% if @coordinator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@coordinator.errors.count, "error") %> prohibited this coordinator from being saved:</h2>

      <ul>
      <% @coordinator.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstname %><br />
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br />
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :street %><br />
    <%= f.text_field :street %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :zipcode %><br />
    <%= f.text_field :zipcode %>
  </div>
  <div class="field">
    <%= f.label :phone_home %><br />
    <%= f.text_field :phone_home %>
  </div>
  <div class="field">
    <%= f.label :phone_mobile %><br />
    <%= f.text_field :phone_mobile %>
  </div>
  <div class="field">
    <%= f.label :phone_work %><br />
    <%= f.text_field :phone_work %>
  </div>
  <div class="field">
    <%= f.label :state_id %><br />
    <%= f.text_field :state_id %>
  </div>
  <div class="field">
    <%= f.label :county_id %><br />
    <%= f.text_field :county_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/coordinators/edit.html.erb
<h1>Editing coordinator</h1>

<%= render 'form' %>

<%= link_to 'Show', @coordinator %> |
<%= link_to 'Back', coordinators_path %>

app/views/coordinators/index.html.erb
<h1>Listing coordinators</h1>

<table>
  <tr>
    <th>Firstname</th>
    <th>Lastname</th>
    <th>Email</th>
    <th>Street</th>
    <th>City</th>
    <th>Zipcode</th>
    <th>Phone home</th>
    <th>Phone mobile</th>
    <th>Phone work</th>
    <th>State</th>
    <th>County</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @coordinators.each do |coordinator| %>
  <tr>
    <td><%= coordinator.firstname %></td>
    <td><%= coordinator.lastname %></td>
    <td><%= coordinator.email %></td>
    <td><%= coordinator.street %></td>
    <td><%= coordinator.city %></td>
    <td><%= coordinator.zipcode %></td>
    <td><%= coordinator.phone_home %></td>
    <td><%= coordinator.phone_mobile %></td>
    <td><%= coordinator.phone_work %></td>
    <td><%= coordinator.state_id %></td>
    <td><%= coordinator.county_id %></td>
    <td><%= link_to 'Show', coordinator %></td>
    <td><%= link_to 'Edit', edit_coordinator_path(coordinator) %></td>
    <td><%= link_to 'Destroy', coordinator, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Coordinator', new_coordinator_path %>

app/views/coordinators/new.html.erb
<h1>Signup to be a coordinator in <%= @county.name %> <%= @county.state.name %></h1>
<div style="width:500px;">

<% semantic_form_for @coordinator do |form| %>
		<%= form.inputs do %>
    <%= form.input :firstname %>
		<%= form.input :lastname %>
		<%= form.input :email %>
		<%= form.input :street, :label => "Street Address" %>
		<%= form.input :city %>
		<%= form.input :state %>
		<%= form.input :zipcode %>
		<%= form.input :phone_home, :label => "Phone Number" %>
		<%= form.input :county_id, :as => :hidden, :input_html => { :value => @county.id } %>
		<% end %>
    <%= form.buttons %>
  <% end %>

</div>

<%= link_to 'Back', coordinators_path %>

app/views/coordinators/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Firstname:</b>
  <%= @coordinator.firstname %>
</p>

<p>
  <b>Lastname:</b>
  <%= @coordinator.lastname %>
</p>

<p>
  <b>Email:</b>
  <%= @coordinator.email %>
</p>

<p>
  <b>Street:</b>
  <%= @coordinator.street %>
</p>

<p>
  <b>City:</b>
  <%= @coordinator.city %>
</p>

<p>
  <b>Zipcode:</b>
  <%= @coordinator.zipcode %>
</p>

<p>
  <b>Phone home:</b>
  <%= @coordinator.phone_home %>
</p>

<p>
  <b>Phone mobile:</b>
  <%= @coordinator.phone_mobile %>
</p>

<p>
  <b>Phone work:</b>
  <%= @coordinator.phone_work %>
</p>

<p>
  <b>State:</b>
  <%= @coordinator.state_id %>
</p>

<p>
  <b>County:</b>
  <%= @coordinator.county_id %>
</p>


<%= link_to 'Edit', edit_coordinator_path(@coordinator) %> |
<%= link_to 'Back', coordinators_path %>