config/routes.rb
Cryout::Application.routes.draw do
  resources :organisers

  resources :coordinators

  resources :counties

  resources :states

  devise_for :users

	match 'states/export' => 'state#export'

   root :to => "states#index"

end

app/models/state.rb
class State < ActiveRecord::Base
	has_many :counties
	has_many :coordinators
	has_one :organiser

	accepts_nested_attributes_for :counties, :coordinators, :organiser
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  # GET /states
  # GET /states.xml
  def index
    @states = State.all
		@counties = County.all
		headers['Content-Type'] = "application/vnd.ms-excel"
    headers['Content-Disposition'] = 'attachment; filename="report.xls"'
    headers['Cache-Control'] = ''
		
  end
	def export
		headers['Content-Type'] = "application/vnd.ms-excel"
    headers['Content-Disposition'] = 'attachment; filename="report.xls"'
    headers['Cache-Control'] = ''
		@states = State.all
	end

  # GET /states/1
  # GET /states/1.xml
  def show
    @state = State.find(params[:id])
		@counties = County.returncounty(params[:id]).sort_by(&:name) 
		


    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @state }
    end
  end

  # GET /states/new
  # GET /states/new.xml
  def new
    @state = State.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @state }
    end
  end

  # GET /states/1/edit
  def edit
    @state = State.find(params[:id])
  end

  # POST /states
  # POST /states.xml
  def create
    @state = State.new(params[:state])

    respond_to do |format|
      if @state.save
        format.html { redirect_to(@state, :notice => 'State was successfully created.') }
        format.xml  { render :xml => @state, :status => :created, :location => @state }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @state.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /states/1
  # PUT /states/1.xml
  def update
    @state = State.find(params[:id])

    respond_to do |format|
      if @state.update_attributes(params[:state])
        format.html { redirect_to(@state, :notice => 'State was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @state.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /states/1
  # DELETE /states/1.xml
  def destroy
    @state = State.find(params[:id])
    @state.destroy

    respond_to do |format|
      format.html { redirect_to(states_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/states/_form.html.erb
<%= form_for(@state) do |f| %>
  <% if @state.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@state.errors.count, "error") %> prohibited this state from being saved:</h2>

      <ul>
      <% @state.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :abreviation %><br />
    <%= f.text_field :abreviation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/states/_report.html.erb
<table border="1">
  <tr>
    <th>County Name</th>
  </tr>
  <% @states.each do |u| %>
		<% u.counties.each do |county|
  <tr>
   <td><%= county.name %></td>
		<% end %>
  <% end %>
 </tr>
</table>

app/views/states/edit.html.erb
<h1>Editing state</h1>

<%= render 'form' %>

<%= link_to 'Show', @state %> |
<%= link_to 'Back', states_path %>

app/views/states/export.html.erb
<%= link_to "Export as Excel", export_state_url %>

app/views/states/index.html.erb
<table border="1">
  <tr>
    <th>State Name</th><th>County Name</th><th>Coordinator Firstname</th><th>Coordinator Last Name</th><th>Address</th><th>Phone</th><th>Email</th><th>City</th><th>Zipcode</th>
  </tr>
  <% @states.each do |u| %>
		<% u.coordinators.each do |coordinator| %>

  <tr>
   <td><%= coordinator.state.name %></td><% if coordinator.county %><td><%= coordinator.county.name %><% else %><td>MISSING</td><% end %><td><%= coordinator.firstname %></td><td><%= coordinator.lastname %></td><td><%= coordinator.street %></td><td><%= coordinator.phone_home %></td><td><%= coordinator.email %></td><td><%= coordinator.city %></td><td><%= coordinator.zipcode %></td>

		<% end %>
  <% end %>
 </tr>
</table>

app/views/states/new.html.erb
<h1>New state</h1>

<%= render 'form' %>

<%= link_to 'Back', states_path %>

app/views/states/show.html.erb
<p id="notice"><%= notice %></p>
<% if @state.organiser.blank? %>
<h2>Your state needs a coordinator!</h2>
<p>We are currently seeking a coordinator for your state. If you are interested in becoming a state coordinator please see the <a href="http://www.awakeningamerica.us/index.php/state_coordinator">list of qualifications here.</a></p>
<% else %>
<h1><%= @state.name %></h1>
<p>Welcome from <%= @state.organiser.firstname %> <%= @state.organiser.lastname %>, the <%= @state.name %> State Coordinator. We are excited to have you working with us to impact <%= @state.name %></p>
<% end %>
<h2>Getting started is easy. Select your county in <%= @state.name %> below:</h2>
<% @counties.each do |county| %>
<%= link_to(county_path(county)) do %>
<p> <%= county.name %></p>
<% end %>
<% end %>
<%= link_to 'Back To Map', states_path %>