config/routes.rb
Cryout::Application.routes.draw do
  resources :organisers

  resources :coordinators

  resources :counties

  resources :states

  devise_for :users

	match 'states/export' => 'state#export'

   root :to => "states#index"

end

app/models/county.rb
class County < ActiveRecord::Base
	belongs_to :state
	has_one :coordinator
	accepts_nested_attributes_for :coordinator
	scope :returncounty, lambda {|state| where(:state_id => state)}
end

app/controllers/counties_controller.rb
class CountiesController < ApplicationController
  # GET /counties
  # GET /counties.xml
  def index
    @counties = County.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @counties }
    end
  end

  # GET /counties/1
  # GET /counties/1.xml
  def show
    @county = County.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @county }
    end
  end

  # GET /counties/new
  # GET /counties/new.xml
  def new
    @county = County.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @county }
    end
  end

  # GET /counties/1/edit
  def edit
    @county = County.find(params[:id])
  end

  # POST /counties
  # POST /counties.xml
  def create
    @county = County.new(params[:county])

    respond_to do |format|
      if @county.save
        format.html { redirect_to(@county, :notice => 'County was successfully created.') }
        format.xml  { render :xml => @county, :status => :created, :location => @county }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @county.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /counties/1
  # PUT /counties/1.xml
  def update
    @county = County.find(params[:id])

    respond_to do |format|
      if @county.update_attributes(params[:county])
        format.html { redirect_to(@county, :notice => 'County was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @county.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /counties/1
  # DELETE /counties/1.xml
  def destroy
    @county = County.find(params[:id])
    @county.destroy

    respond_to do |format|
      format.html { redirect_to(counties_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/counties_helper.rb
module CountiesHelper
end

app/views/counties/_form.html.erb
<%= form_for(@county) do |f| %>
  <% if @county.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@county.errors.count, "error") %> prohibited this county from being saved:</h2>

      <ul>
      <% @county.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :state_id %><br />
    <%= f.text_field :state_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/counties/edit.html.erb
<h1>Editing county</h1>

<%= render 'form' %>

<%= link_to 'Show', @county %> |
<%= link_to 'Back', counties_path %>

app/views/counties/index.html.erb
<h1>Listing counties</h1>

<table>
  <tr>
    <th>Name</th>
    <th>State</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @counties.each do |county| %>
  <tr>
    <td><%= county.name %></td>
    <td><%= county.state_id %></td>
    <td><%= link_to 'Show', county %></td>
    <td><%= link_to 'Edit', edit_county_path(county) %></td>
    <td><%= link_to 'Destroy', county, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New County', new_county_path %>

app/views/counties/new.html.erb
<h1>New county</h1>

<%= render 'form' %>

<%= link_to 'Back', counties_path %>

app/views/counties/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @county.name %> - <%= @county.state.name %> </h1><hr /><br />


<% #Unless this county does not have an active coordinator show the coordinators details to contact them %>
<% unless @county.coordinator.nil? || @county.coordinator.active.nil? %>
<h3>Connect With County Coordinator <%= @county.coordinator.firstname %> <%= @county.coordinator.lastname %></h3>
<p>Would you like to get involved in <%= @county.name %>? We would love your help. Please contact <%= @county.coordinator.firstname %> <%= @county.coordinator.lastname %> using one of the methods below. 
<p><% unless @county.coordinator.email.nil? %>Email <%= @county.coordinator.firstname %>: <a href="mailto:<%= @county.coordinator.email %>"><%= @county.coordinator.email %></a><% end %><br /> <% unless @county.coordinator.phone_home.nil? %>Home Phone: <%= @county.coordinator.phone_home %><% end %></p>


<% #Otherwise, as they have no coordinator, show the coordinator signup process %>
<% else %>
<h2>Your County Still Needs A Coordinator</h2>

You can signup <%= link_to 'here to be a new coordinator', new_coordinator_path(:county_id => @county, :state_id => @county.state) %>!


<!--
<br /><br />
<script type="text/javascript">var host = (("https:" == document.location.protocol) ? "https://secure." : "http://");document.write(unescape("%3Cscript src='" + host + "wufoo.com/scripts/embed/form.js' type='text/javascript'%3E%3C/script%3E"));</script>

<script type="text/javascript">
var m7p1a7 = new WufooForm();
m7p1a7.initialize({
'userName':'socialmedia101', 
'formHash':'m7p1a7', 
'autoResize':true,
'height':'907', 
'ssl':true});
m7p1a7.display();
</script>

-->


<% end %>
<br />
<%= link_to 'Back', states_path %>